### ISSUE TITLE
Now Playing 2 doesn't pull the metadata of the tracks from CDJ 3000 when using Cloud Direct Play streaming as a source

### ISSUE THREAD

**Issue by DjVoytech** [AzuraCast/nowplaying#13]
Are there any masterminds who can figure out how to modify Now Playing 2 that would make it work with Cloud Direct Play on CDJ 3000. It is working fine when playing music from USB or Rekordbox with CDJ 3000 in HID mode but Now playing 2 refuse to gather tracklists from DJ pro link when the Cloud Direct Play source is selected on the CDJ 3000.

I attached a screenshot of the logs when I load the track from the Cloud on the CDJ 3000

Any modification to the program that would make it work would be much appreciated. 

![Now Playing 2 logs](https://github.com/user-attachments/assets/a85442b1-33c8-4e24-a119-558c68b8973f)

**Comment by BusterNeece** [comment]
@DjVoytech That is most definitely a different piece of software than this one.
