### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by JulianBorghuis** [AzuraCast/nowplaying#6]
Wich folder do i need to enter to install this? And are there requirements?

**Comment by BusterNeece** [comment]
@julianborghuis This isn't a library intended for end-users to use directly; this is a PHP component intended for inclusion in other PHP applications. It's installed using the Composer package manager for PHP.

If you're looking to install AzuraCast itself, you can do so by visiting [the project's homepage](https://azuracast.com/).
