### ISSUE TITLE
Use admin passwort in Shoutcast2 adapter if set

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/nowplaying#7]
This issue is prompted by [this](https://github.com/AzuraCast/AzuraCast/issues/2515) AzuraCast issue.

The Shoutcast2 adapter is currently not using the admin password if it is set. The IceCast adapter uses it if it is set. In order to still access the API when the puplic access to it is blocked the `pass` query parameter should be set.

**Comment by BusterNeece** [comment]
Implemented in latest commit.
