### ISSUE TITLE
Now Playing Update /admin/stats API call fails due to URL-encoded basic authentication parameters 

### ISSUE THREAD

**Issue by Jamie0** [AzuraCast/nowplaying#9]
This issue seems to particularly affect AzuraMirror. 

We patched status.xsl, xspf.xsl, status-json.xsl and status2.xsl to hide listener statistics from curious members of the public. Consequently, the Now Playing Update command won't run owing to listeners being NULL on the JSON now playing data.

But as the Icecast adapter has HTTP basic authentication available, it should be first trying `/admin/stats`. This appears to be failing due to `source:password` being in an urlencoded format before being parsed in [this file.](https://github.com/AzuraCast/nowplaying/blob/main/src/Adapter/AdapterAbstract.php#L39), resulting in an empty password being supplied and a 401 error. 

I fixed this by wrapping $uriUserInfo in urldecode before it is exploded.

**Comment by BusterNeece** [comment]
@Jamie0 The URI standard actually seems to suggest that the userinfo part of the URL shouldn't be encoded when pulled from the URI. When I test it with AzuraCast itself, when I pass a username and password, it comes through directly and not URLencoded in the URI.

I think we may have a specific issue with AzuraRelay that needs to be fixed there.

**Comment by Jamie0** [comment]
Good point, let's open an issue on that repo!
